### ISSUE TITLE
No such file or directory: 'content/www.macrumors.com-roundup-ipad-

### ISSUE THREAD

**Issue by temirov** [technovangelist/videoprojects#9]
(venv) tyemirov@computercat:~/agents/videoprojects/2024-04-04-build-rag-with-python$ python3 import.py            

FileNotFoundError: [Errno 2] No such file or directory: 'content/www.macrumors.com-roundup-ipad-

**Comment by pranavkr29** [comment]
I have the same issue.

**Comment by temirov** [comment]
@pranavkr29  gave  the correct  answer. @technovangelist  please, add an empty content folder to the repo (putting an empty .gitkeep file is customary)

```shell
mkdie content
touch content/.gitkeep

git add content/.gitkeep
git commit -m "Add empty content  folder to download articles"
```
